### ISSUE TITLE
headers: false = display in the inline editor is ignored

### ISSUE THREAD

**Issue by gbdesign2023** [bogdancondorachi/kirby-table-field#8]
I have found a small, cosmetic problem: 
With the setting "headers: false" in the blueprint, the first line is still displayed as a header in the inline editor. In the dialog editor, the display is correct.

```
  table:
    label: Tabelle
    type: table
    headers: false
```

<img width="1348" alt="screenshot" src="https://github.com/bogdancondorachi/kirby-table-field/assets/140849227/3ea31ef4-0fdd-411b-87c4-6fbc06f8fc0f">
